version: "3.5"

services:
  manga-reader:
    build:
      context: .
      target: prod
    hostname: "manga-reader"
    container_name: "manga-reader"
    profiles:
      - test
    environment:
      DB_FILE_PATH: "test.db"
      WEB_PORT: 5678
      WEB_CORS: true
      WEB_PROXY: true
      DB_DEBUG: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tests/helpers/repo/test.db:/app/test.db
    ports:
      - "5678:5678"
    command:
      - /app/manga-reader